---
- name: Set _bastion_student_user_password if password has been provided
  when: bastion_student_user_password | default("") | length > 0
  ansible.builtin.set_fact:
    _bastion_student_user_password: "{{ bastion_student_user_password }}"

- name: Generate _bastion_student_user_password if not defined
  when: bastion_student_user_password | default("") | length == 0
  ansible.builtin.set_fact:
    _bastion_student_user_password: "{{ lookup('password', '/dev/null length=' ~ bastion_student_user_password_length ~' chars=ascii_letters,digits') }}"

- name: Create student user
  ansible.builtin.user:
    name: "{{ bastion_student_user_name }}"
    password: "{{ _bastion_student_user_password | password_hash('sha512') }}"
    comment: Red Hat Demo Platform Student
    group: users
    groups: "{{ 'wheel' if bastion_student_user_sudo | bool else '' }}"
    shell: /bin/bash
    state: present

- name: Add student public key if provided
  when: bastion_student_user_key | default("") | length > 0
  ansible.posix.authorized_key:
    user: "{{ bastion_student_user_name }}"
    key: "{{ bastion_student_user_key }}"

- name: Enable password authentication
  ansible.builtin.lineinfile:
    line: PasswordAuthentication yes
    regexp: '^ *PasswordAuthentication'
    path: /etc/ssh/sshd_config

- name: Remove PasswordAuthentication line from 50-cloud-init.conf
  when: bastion_remove_cloud_init_conf | bool
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    regexp: PasswordAuthentication
    state: absent

- name: Disable root password authentication
  ansible.builtin.lineinfile:
    line: PermitRootLogin without-password
    regexp: '^ *PermitRootLogin'
    path: /etc/ssh/sshd_config

- name: Allow passwordless sudo
  when: bastion_student_user_sudo | bool
  ansible.builtin.lineinfile:
    path: '/etc/sudoers'
    state: present
    line: "{{ bastion_student_user_name }}         ALL=(ALL)       NOPASSWD: ALL"
    insertafter: "'^{{ ansible_user }}"

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Print and set access user info
  vars:
    _bastion_inventory_name: "{{ groups['bastions'][0] }}"
  block:
  - name: Set _bastion_public_hostname from inventory (not an OpenShift cluster config)
    when: cluster_dns_zone | default("") | length == 0
    ansible.builtin.set_fact:
      _bastion_public_hostname: >-
            {{ hostvars[groups.bastions.0].public_dns_name
            | default(hostvars[groups.bastions.0].public_ip_address)
            }}

  - name: Set _bastion_public_hostname from cluster_dns_zone
    when: cluster_dns_zone | default("") | length > 0
    block:
    - name: Set bastion hostname (AWS)
      when: cloud_provider == 'aws'
      ansible.builtin.set_fact:
        _bastion_public_hostname: "{{ hostvars[_bastion_inventory_name].shortname }}.{{ cluster_dns_zone }}"

    - name: Set bastion hostname (CNV)
      when: cloud_provider == 'openshift_cnv'
      ansible.builtin.set_fact:
        _bastion_public_hostname: "{{ openshift_cnv_ssh_address }}"

    - name: Set bastion hostname (Azure or GCP)
      when: cloud_provider == "azure" or cloud_provider == "gcp"
      ansible.builtin.set_fact:
        _bastion_public_hostname: "bastion.{{ cluster_dns_zone }}"

    - name: Set bastion hostname (Fallback)
      when: _bastion_public_hostname | length == 0
      ansible.builtin.set_fact:
        _bastion_public_hostname: "{{ hostvars[_bastion_inventory_name].shortname }}.{{ cluster_dns_zone }}"

  - name: Print access info (non CNV)
    when:
    - bastion_student_user_show_user_info | bool
    - not cloud_provider == "openshift_cnv"
    agnosticd.core.agnosticd_user_info:
      msg: |
        You can access your bastion via SSH:
        ssh {{ bastion_student_user_name }}@{{ _bastion_public_hostname }}

        Use password '{{ _bastion_student_user_password }}' when prompted.

  - name: Print access info (CNV)
    when:
    - bastion_student_user_show_user_info | bool
    - cloud_provider == "openshift_cnv"
    agnosticd.core.agnosticd_user_info:
      msg: |
        You can access your bastion via SSH:
        ssh {{ bastion_student_user_name }}@{{ _bastion_public_hostname }} -p {{ hostvars[groups['bastions'][0]].bastion_ssh_port }}

        Use password '{{ _bastion_student_user_password }}' when prompted.

  - name: Set access data
    when: bastion_student_user_set_user_data | bool
    agnosticd.core.agnosticd_user_info:
      data:
        bastion_public_hostname: "{{ _bastion_public_hostname }}"
        bastion_ssh_password: "{{ _bastion_student_user_password }}"
        bastion_ssh_user_name: "{{ bastion_student_user_name }}"
        bastion_ssh_pubkey_content: "{{ bastion_ssh_pubkey_content }}"

  - name: Set bastion port for CNV
    when: cloud_provider == "openshift_cnv"
    agnosticd.core.agnosticd_user_info:
      data:
        bastion_ssh_port: "{{ hostvars[groups['bastions'][0]].bastion_ssh_port }}"
